# This is a basic workflow to help you get started with Actions 
name: Add SubDomain
# Controls when the workflow will run
on:
  push:
    branches: ['master']
    paths: ['script/*.yml', 'script/*.sh', '.github/workflows/*.yml','domain/domainlist.txt',]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Read sample.yml
      id: sample
      uses: juliangruber/read-file-action@v1
      with:
        path: ./script/sample.yml
  
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
          find: "foo.com"
          replace: "fofofofofofo.com"
          regex: false
          include: "sample.yml"
          
        
    - name: Echo sample.yml
      run: echo "${{ steps.sample.outputs.content }}" >  sample4.yml

    # Runs commands using the runners shell
    - name: commit new file
      run: |           
          git config --local user.name  ${{ github.actor }}  
          git add "sample4.yml"
          git commit -m "Commit message"          
          
    # chmod +x ./script/addcrt.sh
          
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
