name: Greeting on variable day

on:
  push:
    branches: ['master']
    paths: ['script/*.yml', 'script/*.sh', '.github/workflows/*.yml','domain/domainlist.txt',]

env:
    DIMAIN_NAME: test.com

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "get the domain name"
        run: echo "$DIMAIN_NAME"
