name: Greeting on variable day

on:
  push:
    branches: ['master']
    paths: ['script/*.yml', 'script/*.sh', '.github/workflows/*.yml','domain/domainlist.txt',]

env:
    DOMAIN_NAME: test.com

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "get the domain name"
   #     run: echo "$DOMAIN_NAME"
        run:  |
          $(cat akamai/script/sample.yml | sed 's/foo.com/'$DOMAIN_NAME'/g' > /crt/$DOMAIN_NAME.yml)
          echo $DOMAIN_NAME.yml > $DOMAIN_NAME.yml
