name: Add Domain

on:
  push:
    branches: ['master']
    paths: ['.github/workflows/*.yml','domain/domainlist.txt',]

env:
    DOMAIN_NAME: test-me1.com
    contractId: V-40T9211
    edgeHostnameId: 5032864
    property_name: custom-hostname

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone the repository"
        uses: actions/checkout@v2

      - name: "Get the domain name and create yml file for the crt"
        run:  |
          git config --local user.name  ${{ github.actor }}
          #   echo $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/script/
          touch $GITHUB_WORKSPACE/crt/$DOMAIN_NAME.yml
          ls -lah $GITHUB_WORKSPACE/crt/
          $(cat $GITHUB_WORKSPACE/script/sample.yml | sed 's/foo.com/'$DOMAIN_NAME'/g' > $GITHUB_WORKSPACE/crt/$DOMAIN_NAME.yml)
          cat  $GITHUB_WORKSPACE/crt/$DOMAIN_NAME.yml
      #    echo $DOMAIN_NAME.yml > $DOMAIN_NAME.yml
      # Runs commands using the runners shell
      - name: Run the build shell script
        run: |
            git add  "$GITHUB_WORKSPACE/crt/$DOMAIN_NAME.yml"
            git commit -m "$(date +'%d/%m/%Y') $DOMAIN_NAME.yml Added"
            
      - name: Push changes  # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            force: true
            
      # Apply CRT to Akamai
      - name: Apply CRT to Akamai
        run: |
          akamai cps create --file $GITHUB_WORKSPACE/crt/$DOMAIN_NAME.yml --contract-id $contractId --force --section default
