name: Greeting on variable day

on:
  push:
    branches: ['master']
    paths: ['script/*.yml', 'script/*.sh', '.github/workflows/*.yml','domain/domainlist.txt',]

env:
  # DAY_OF_WEEK: Monday
    DIMAIN_NAME: test.com

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DIMAIN_NAME!"
        env:
          First_Name: Mona
