# This is a basic workflow to help you get started with Actions 
name: Add SubDomain
# Controls when the workflow will run
on:
  push:
    branches: ['master']
    paths: ['script/*.yml', 'script/*.sh', '.github/workflows/*.yml','domain/domainlist.txt',]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs commands using the runners shell
    - name: commit new file
      run: |      
           chmod +x "${GITHUB_PATH}/run.sh"
